// Generated by CoffeeScript 1.4.0
(function() {

  window.A = {
    addData: function(label, object) {
      if (!A.objects) {
        A.objects = {};
      }
      return A.objects[label] = object;
    },
    getData: function(label) {
      return A.objects[label];
    },
    getOne: function(label) {
      var object;
      object = A.getData(label);
      return object[Object.keys(object)[0]];
    },
    addFunction: function(label, fn) {
      if (!A.functions) {
        A.functions = {};
      }
      return A.functions[label] = fn;
    },
    getFunction: function(label) {
      return A.functions[label];
    },
    bind: function(object, evnt, fn) {
      return object.addEventListener(evnt, fn, false);
    },
    click: function(selector) {
      return A.bind(A.select(selector), 'click', A.functions[selector]);
    },
    visible: function(object) {
      return object.style.display !== 'none';
    },
    select: function(selector) {
      return document.getElementsByClassName(selector)[0];
    },
    each: function(items, fn) {
      var item, _results;
      _results = [];
      for (item in items) {
        _results.push(fn(items[item]));
      }
      return _results;
    },
    hideAll: function(items) {
      return A.each(items, A.hide);
    },
    hide: function(item) {
      return item.style.display = 'none';
    },
    showAll: function(items) {
      return A.each(items, A.show);
    },
    show: function(item) {
      return item.style.display = 'block';
    },
    fill: function(items) {
      var item, object, _i, _len;
      object = {};
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        object[item] = A.select(item);
      }
      return object;
    },
    find: function(object, item) {
      return object[item];
    }
  };

  A.bind(window, 'load', function() {
    A.addData('elements', A.fill(['html', 'css', 'js']));
    A.addData('rubyElements', A.fill(['haml', 'scss', 'cs']));
    A.hideAll(A.getData('elements'));
    A.addFunction('toggle', function(evnt) {
      if (A.visible(A.getOne('elements'))) {
        A.hideAll(A.getData('elements'));
        A.showAll(A.getData('rubyElements'));
      } else {
        A.hideAll(A.getData('rubyElements'));
        A.showAll(A.getData('elements'));
      }
      return false;
    });
    return A.click('toggle');
  });

}).call(this);
